### PR TITLE
Don't use ExUnit in production code

### PR DESCRIPTION
**Pull request by tshakah**
This changes the use of `assert` to raise on `nil`, and removes the commented out asserts

I'm actually not sure what tests to write to get this to fail

### CODE REVIEW

**Comment by g-andrade** [comment]
It's OK, I think there's no need to test it since the check is only there to ensure that, in the rare event that the caller of this module is handling it wrong, a more obscure exception won't be produced in later stages of decoding - it is indeed an assertion.

Now, for some reason CI isn't being triggered... I'm going to close and reopen the PR so see if that does it.

**Comment by tshakah** [comment]
You can get structs to be covered by using them in pattern matches in tests, I'll push a commit with an example

**Comment by tshakah** [comment]
Those two commits have gotten me another 1% coverage locally

**Comment by g-andrade** [comment]
> You can get structs to be covered by using them in pattern matches in tests, I'll push a commit with an example

Ohh, thanks for the tip! And for your contribution as well. I’ll merge it and tag a new version tomorrow if I get a chance; if not, later this week for sure.

**Comment by g-andrade** [comment]
Closes #19

**Comment by g-andrade** [comment]
`0.1.3` tagged and published to Hex :tada:

**Comment by tshakah** [comment]
Thanks 🎉

**Pull request merged**
